name: ebisu_capnp
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_capnp
dependencies:

# custom <ebisu_capnp dependencies>

  id: "^1.0.9"
  ebisu: "^0.6.5"
  ebisu_cpp: "^0.3.0"
  crypto: "^0.9.1"

# end <ebisu_capnp dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_capnp dev dependencies>

  test: "^0.12.0"

# end <ebisu_capnp dev dependencies>

dependency_overrides:
# custom <ebisu_capnp dependency overrides>
# end <ebisu_capnp dependency overrides>

transformers:

# custom <ebisu_capnp transformers>
# end <ebisu_capnp transformers>

